# Generated by Django 4.2 on 2023-05-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0010_emprestimo_avaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateField(auto_now_add=True, default='2023-05-16'),
            preserve_default=False,
        ),
    ]
