# Generated by Django 4.2 on 2023-05-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0011_alter_emprestimo_data_emprestimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='avaliacao',
            field=models.CharField(blank=True, choices=[('P', 'Péssimo'), ('R', 'Ruim]'), ('B', 'Bom'), ('O', 'Ótimo')], max_length=1, null=True),
        ),
    ]
